name: Container Image CI

on:
  push:
    branches: [ "main" ]
    paths: [ "Dockerfile", ".github/workflows/container-image.yml" ]
  pull_request:
    branches: [ "main" ]
    paths: [ "Dockerfile", ".github/workflows/container-image.yml"]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Build and Push
        uses: docker/build-push-action@v5
        with:
          push: true
          context: .
          file: ./Dockerfile
          tags: ghcr.io/${{ github.repository_owner }}/c4e-dev:latest
